baseURL = 'https://fmagno.github.io/me/'
# baseURL = '/'
languageCode = 'en-us'
title = 'Bite size Q&A'
theme = ['hugo-shortcode-roneo-collection', 'terminal']
# theme = "terminal"
themeColor = "orange"
paginate = 5
centerTheme = true
Toc = true



[languages]
  [languages.en]
    languageName = "English"
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "fmagno"
      logoHomeLink = "/me/about"

    [languages.en.menu]
        [[languages.en.menu.main]]
            identifier = "about"
            name = "about"
            url = "/about"
        [[languages.en.menu.main]]
            identifier = "posts"
            name = "posts"
            url = "/posts"
        [[languages.en.menu.main]]
            identifier = "projs"
            name = "projs"
            url = "/projs"

[markup.goldmark.parser.attribute]
block = true
title = true
